### PR TITLE
Debian package build settings

### PR DESCRIPTION
**Pull request by cmrd-senya**
Changes CMake settings so that we can build proper .deb package for Debian using CPack.

### CODE REVIEW

**Comment by dirkvdb** [comment]
Are you going to create a pull request every time the depending versions change?

I will not accept the release cxx flags modification. Use another way to set it if you really want to.

**Comment by cmrd-senya** [comment]
Well, I don't promise I'll maintain that on a regular basis, but if there are any issues with the packages versions you can ping me and I'll try to update it.

The only thing I don't quite like about it, is that these versions stick to Debian, while there are other deb-based distributions. CPack doesn't seem to handle it direclty, but maybe I can use some build-time directives to make this explicit?

**Comment by dirkvdb** [comment]
I decided not to merge this PR. I cannot maintain these kind of settings for every distribution.
You should simply maintain these variables in a cmake file yourself and inject the variables in the cache using the `cmake -C` command line option.

**Comment by cmrd-senya** [comment]
Okay, thanks anyway for considering this!

**Pull request closed without merging**
