### PR TITLE
Support for continuous thumbnail creation

### PR DESCRIPTION
**Pull request by cmrd-senya**
This adds new -r command line argument which enables making thumbnails each N seconds.
Default value of 0 preserves the original behavior.

### CODE REVIEW

**Comment by dirkvdb** [comment]
I feel like this could easily be achieved with some wrapper around the ffmpegthumbnailer binary.
I don't really like the eternal while loop construction, when there is no proper signal handling implemented.

**Comment by cmrd-senya** [comment]
The problem is that overheads on loading the binary, reopening the stream everytime and doing all the preparations are quite high. I do snapshots every 10 seconds and achieving this with a wrapper would be really inefficient solution.

I can add some signal handling, if it is a blocker.

**Comment by dirkvdb** [comment]
I will merge it when I find the time.

**Comment by cmrd-senya** [comment]
Thank you!

**Comment by dirkvdb** [comment]
Sorry for the delay :-)

**Pull request merged**
