### PR TITLE
correct field name in setProperties function

### PR DESCRIPTION
**Pull request by aedis**
- use proper field name for setPreferEmbeddedMetadata method

### CODE REVIEW

**Comment by dirkvdb** [comment]
Thanks!

**Comment by aedis** [comment]
Why did you close it without merge?

**Comment by dirkvdb** [comment]
I merged it

**Comment by aedis** [comment]
It's closed, not merged.

**Comment by dirkvdb** [comment]
My bad, I thought I pushed the button :-)

**Comment by aedis** [comment]
No problem :)

**Pull request merged**
